title: Vivek Reddy
logo: "/images/portrait.jpg?raw=true" 
 # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist designing predictive models, generative AI pipelines, and scalable analytics systems
  <br><br>
  
  <a href="/about_me" style="font-size: 18px;">About Me</a>
  <br><br>
  <a href="/pdf/vivek_resume.pdf" style="font-size: 18px;">View My Resume</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/vivek-reddy/" style="font-size: 18px;">View My LinkedIn Profile</a>


url: "https://vivektreddy.github.io"
baseurl: ""   # must be empty for user sites

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-T70BN1HJ0K  
